import{demoClients}from'../domain/demo-clients.js';

const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const norm=value=>String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();

export function initClientCommand({available,onAsk}){
  const root=document.createElement('div');root.className='client-command';root.hidden=true;root.innerHTML=`<section class="client-command-shell" role="dialog" aria-modal="true" aria-labelledby="client-command-title"><header><span>⌘</span><input id="client-command-input" aria-label="Buscar clientes" placeholder="Busca cliente, empresa, señal…" autocomplete="off"><kbd>ESC</kbd></header><div class="client-command-meta"><strong id="client-command-title">CLIENT SIGNALS</strong><span>30 perfiles · análisis WhatsApp</span></div><main><div class="client-results" id="client-results"></div><aside class="client-preview" id="client-preview"></aside></main><footer><span><kbd>↑</kbd><kbd>↓</kbd> navegar</span><span><kbd>↵</kbd> abrir</span><b><i></i> WhatsApp signal index</b></footer></section>`;document.body.append(root);
  const input=root.querySelector('input'),results=root.querySelector('#client-results'),preview=root.querySelector('#client-preview');let matches=[...demoClients],active=0;
  const statusTone=status=>status==='En riesgo'?'risk':status==='Cliente'?'client':'live';
  function renderPreview(client){preview.innerHTML=`<div class="client-orbit"><span>${esc(client.name.split(' ').map(part=>part[0]).join('').slice(0,2))}</span><i></i><i></i></div><span class="client-status ${statusTone(client.status)}">${esc(client.status)}</span><h2>${esc(client.name)}</h2><p>${esc(client.role)} · ${esc(client.company)}</p><div class="client-value"><span>OPORTUNIDAD</span><strong>${esc(client.value)}</strong><small>${esc(client.sentiment)}</small></div><div class="client-insight"><span>WHATSAPP ANALYSIS</span><p>${esc(client.summary)}</p></div><div class="client-next"><span>NEXT BEST ACTION</span><strong>${esc(client.next)}</strong></div><button data-client-ask>Trabajar con Lumen <span>→</span></button>`}
  function render(){results.innerHTML=matches.length?matches.map((client,index)=>`<button class="client-result ${index===active?'active':''}" data-client-index="${index}"><span>${esc(client.name.split(' ').map(part=>part[0]).join('').slice(0,2))}</span><div><strong>${esc(client.name)}</strong><small>${esc(client.company)} · ${esc(client.tags.join(' / '))}</small></div><em>${esc(client.last)}</em></button>`).join(''):'<div class="client-empty"><span>⌁</span><strong>Sin señales todavía</strong><small>Prueba otro nombre, empresa o intención.</small></div>';if(matches[active])renderPreview(matches[active]);else preview.innerHTML=''}
  function search(){const query=norm(input.value.trim());matches=demoClients.filter(client=>norm([client.name,client.company,client.role,client.status,client.sentiment,...client.tags].join(' ')).includes(query));active=0;render()}
  function open(){if(!available())return;root.hidden=false;document.body.classList.add('client-command-open');input.value='';matches=[...demoClients];active=0;render();requestAnimationFrame(()=>{root.classList.add('visible');input.focus()})}
  function close(){root.classList.remove('visible');document.body.classList.remove('client-command-open');setTimeout(()=>root.hidden=true,220)}
  input.addEventListener('input',search);
  root.addEventListener('click',event=>{if(event.target===root)return close();const item=event.target.closest('[data-client-index]');if(item){active=Number(item.dataset.clientIndex);render();results.children[active]?.scrollIntoView({block:'nearest'})}if(event.target.closest('[data-client-ask]')&&matches[active]){onAsk(matches[active]);close()}});
  document.addEventListener('click',event=>{if(event.target.closest('[data-client-search]'))open()});
  document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();root.hidden?open():close();return}if(root.hidden)return;if(event.key==='Escape'){event.preventDefault();close()}if(matches.length&&(event.key==='ArrowDown'||event.key==='ArrowUp')){event.preventDefault();active=(active+(event.key==='ArrowDown'?1:-1)+matches.length)%matches.length;render();results.children[active]?.scrollIntoView({block:'nearest'})}if(event.key==='Enter'&&matches[active]){event.preventDefault();onAsk(matches[active]);close()}});
  document.querySelector('.vault-os-actions')?.insertAdjacentHTML('afterbegin','<button class="vault-client-search" data-client-search><span>⌕</span> Clientes <kbd>Ctrl K</kbd></button>');render();
}
