import {clients,scenarios} from './domain/clients.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='vault-business-demo-v1',blank=()=>({connected:false,selected:'acme',scenario:'followup',mode:'followup',records:{}});
let state=blank();try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&clients.some(c=>c.id===saved.selected))state={...state,...saved}}catch{}
let section=0,scene,online=false,busy=false,requestRun=0,recording=false,media,recorder,chunks=[],audioBlob,audioURL,recordTimer,permissionRun=0,searchIndex=0,searchItems=[],pendingScenario=null,workspaceOpen=false,captureContext,levelFrame;
const client=()=>clients.find(c=>c.id===state.selected)||clients[0];
const record=()=>state.records[state.selected]||(state.records[state.selected]={notes:[],agreements:[],drafts:{},transcript:'',translation:'',target:'Español',tone:'Directo y cercano'});
const save=()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{toast('El navegador no pudo guardar. Exporta tus acuerdos antes de cerrar.')}};
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function closeDialogs(){ $$('dialog[open]').forEach(d=>d.close()) }
function showDialog(id){closeDialogs();$(id).showModal()}
function navigate(index){section=Math.max(0,Math.min(3,index));$$('.chapter').forEach((el,i)=>el.hidden=i!==section);$$('[data-section]', $('.navigation')).forEach(b=>{if(+b.dataset.section===section)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});$('#chapter-number').textContent='0'+(section+1)+' / 04';$('.chapter-track i').style.width=(section+1)*25+'%';$('#chapter-caption').textContent=['Tu agente está listo para convertir una señal en movimiento.','Conecta sólo lo necesario; el contexto empieza a moverse.','Lumen recupera el hilo para que tú puedas decidir.','Propuestas claras. Acuerdos que puedes revisar y confirmar.'][section];$('#previous-section').disabled=section===0;$('#next-section').disabled=section===3;$('.navigation').classList.toggle('scrolled',$$('.chapter')[section].scrollTop>10);history.replaceState(null,'','#'+$$('.chapter')[section].id)}
$$('.chapter').forEach(el=>el.addEventListener('scroll',()=>$('.navigation').classList.toggle('scrolled',el.scrollTop>10),{passive:true}));
$('#previous-section').onclick=()=>navigate(section-1);$('#next-section').onclick=()=>navigate(section+1);
import('./ui/scene.js').then(({PulseScene})=>{try{scene=new PulseScene($('#hero-canvas'));$('#hero-canvas').parentElement.addEventListener('pointermove',e=>{const box=e.currentTarget.getBoundingClientRect();scene.setPointer((e.clientX-box.left)/box.width*2-1,(e.clientY-box.top)/box.height*2-1)})}catch{}}).catch(()=>{});
const hash=$$('.chapter').findIndex(el=>location.hash==='#'+el.id);navigate(hash<0?0:hash);
function login(){
  $('#gateway-content').innerHTML='<span class="wordmark"><span class="glyph">✳</span> gnx<span class="brand-dot">/vault</span></span><div class="gateway-steps"><i class="active"></i><i class="active"></i><i class="active"></i></div><span class="eyebrow">LUMEN ESTÁ LISTO</span><h2>¿Qué quieres<br><em>mover hoy?</em></h2><p>Entra a un espacio donde Lumen reúne el hilo, prepara una propuesta y te deja confirmar el siguiente paso.</p><div class="consent-list"><span>✓ Tú revisas cada propuesta antes de usarla.</span><span>✓ El contexto y los acuerdos permanecen visibles.</span><span>✓ Las conexiones se activan sólo cuando tú las autorizas.</span></div><button class="button" id="login-enter">Hablar con Lumen <span>↗</span></button><p class="fine">Vista previa local con conversaciones de ejemplo. No se conecta ni se envía nada sin tu acción.</p>';
  showDialog('#gateway');$('#login-enter').addEventListener('click',()=>{closeDialogs();enter();if(pendingScenario){chooseScenario(pendingScenario);pendingScenario=null}});
}
function enter(){if(!state.connected){state.connected=true;save()}workspaceOpen=true;$('#landing').hidden=true;$('#workspace').hidden=false;render();$('#action-panel').focus?.();health()}
function goHome(){cancelRecording();requestRun++;busy=false;workspaceOpen=false;$('#workspace').hidden=true;$('#landing').hidden=false;$('.navigation .wordmark').focus()}
function qr(){
  const cells=[];for(let y=0;y<21;y++)for(let x=0;x<21;x++){const finder=(ox,oy)=>x>=ox&&x<ox+7&&y>=oy&&y<oy+7&&((x===ox||x===ox+6||y===oy||y===oy+6)||(x>=ox+2&&x<=ox+4&&y>=oy+2&&y<=oy+4));if(finder(0,0)||finder(14,0)||finder(0,14)||((x*17+y*13+x*y)%7<3&&!(x<8&&y<8)&&!(x>12&&y<8)&&!(x<8&&y>12)))cells.push('<rect x="'+x+'" y="'+y+'" width="1" height="1"/>')}
  $('#gateway-content').innerHTML='<span class="eyebrow">AÑADIR UNA SEÑAL</span><h2>Una conexión.<br><em>Todo el hilo.</em></h2><p>Elige qué conversación podrá consultar Lumen. Cada conexión debe ser clara, limitada y revocable.</p><div class="qr-demo" role="img" aria-label="Ilustración de una conexión local de vista previa, no escaneable"><svg viewBox="0 0 21 21" fill="#13251b">'+cells.join('')+'</svg><b>VISTA PREVIA</b></div><button class="button" id="qr-confirm">Cargar conversaciones de ejemplo <span>✓</span></button><p class="fine">Este recorrido usa tres conversaciones ficticias. No se leen ni envían mensajes reales.</p>';
  showDialog('#gateway');$('#qr-confirm').onclick=()=>{state.connected=true;save();closeDialogs();render();toast('Conversaciones de ejemplo listas para Lumen.')};
}
function focusAction(){if(innerWidth<=850)$('#action-panel').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});$('#action-panel').scrollTop=0}
function chooseScenario(id){if(!scenarios[id])return;if(!workspaceOpen){pendingScenario=id;login();return}cancelRecording();requestRun++;busy=false;closeDialogs();state.scenario=id;state.selected=scenarios[id].client;state.mode=scenarios[id].mode;save();render();if(state.connected)focusAction();toast('Escenario: '+scenarios[id].label)}
function selectClient(id){if(!clients.some(c=>c.id===id))return;cancelRecording();requestRun++;busy=false;state.selected=id;save();render();$('#client-main').scrollTop=0;$('.workspace-grid').scrollTop=0;$('#action-panel').scrollTop=0}
function render(){
  const c=client(),r=record();$('#scenario-label').textContent=scenarios[state.scenario]?.label||'Tu siguiente movimiento';$('#client-count').textContent=state.connected?'03':'00';
  $('#connect-whatsapp').innerHTML='<span class="channel-dot">↗</span><span><strong>'+(state.connected?'Añadir otra conexión':'Añadir una conexión')+'</strong><small>'+(state.connected?'3 conversaciones en vista previa':'Visible y revocable')+'</small></span><span>＋</span>';
  $('#client-list').innerHTML=state.connected?clients.map(c=>'<button class="client-row '+(state.selected===c.id?'active':'')+'" data-client="'+c.id+'" '+(state.selected===c.id?'aria-current="true"':'')+'><span class="mini-avatar '+c.color+'">'+c.initials+'</span><span><strong>'+c.name+'</strong><small>'+c.company+'</small></span></button>').join(''):'';
  const progressed=state.connected? r.agreements.length?4:Object.keys(r.drafts).length||r.notes.length?3:2:0;
  $$('#journey li').forEach((el,i)=>el.classList.toggle('done',i<progressed));
  if(!state.connected){$('#client-main').innerHTML='<div class="empty-state"><span class="glyph">✳</span><span class="eyebrow">PRIMERA SEÑAL</span><h2>Dale a Lumen<br>algo con qué trabajar.</h2><p>Conecta una conversación para que pueda recuperar el contexto y prepararte un siguiente paso claro.</p><button class="button" data-connect>Añadir una conexión <span>↗</span></button><p class="fine">La vista previa carga conversaciones ficticias; ninguna cuenta se vincula.</p></div>';$('#action-panel').innerHTML='<span class="eyebrow">UNA DIRECCIÓN CLARA</span><h2>Señal. Contexto.<br>Acuerdo.</h2><p class="fine">Lumen convierte lo que ya ocurrió en una propuesta que tú puedes revisar.</p><div class="context-card"><h3>01 · Recupera el hilo</h3><p class="fine">Una conversación y sus antecedentes, juntos.</p><h3>02 · Prepara una propuesta</h3><p class="fine">Una respuesta o briefing que conserva las incertidumbres.</p><h3>03 · Confirma el siguiente paso</h3><p class="fine">Un acuerdo visible, con responsable y fecha.</p></div>';return}
  $('#client-main').innerHTML='<div class="client-heading"><span class="mini-avatar '+c.color+'">'+c.initials+'</span><div><h1>'+c.name+'</h1><p>'+c.company+' · '+c.language+'</p></div><span class="pill">VISTA PREVIA</span></div><div class="context-card"><span class="eyebrow">LO QUE IMPORTA AHORA</span><h3>'+c.summary+'</h3><div class="context-tags">'+c.tags.map(t=>'<span>'+t+'</span>').join('')+'<span>'+r.notes.length+' notas confirmadas</span></div></div><div class="source-heading"><span class="eyebrow">EL HILO ORIGINAL</span><span>Conversación · Vista previa local</span></div>'+c.messages.map(m=>'<article class="message '+(m.from==='me'?'out':'')+'"><header><span>'+(m.from==='me'?'Tú':c.name.split(' ')[0])+'</span><time>'+m.time+'</time></header><p>'+escape(m.text)+'</p></article>').join('')+r.notes.map((n,i)=>'<article class="saved-note"><small>NOTA CONFIRMADA · '+new Date(n.at).toLocaleDateString('es-MX')+'</small>'+escape(n.text)+'<div><button class="text-button" data-delete-note="'+i+'">Eliminar nota</button></div></article>').join('')+'<p class="source-note">Vista previa local: las notas que confirmes se incorporan al contexto de esta conversación.</p>';
  renderAction();
}
function renderAction(){
  if(recording)recorder.stop();else permissionRun++;
  const c=client(),r=record(),mode=state.mode,draft=r.drafts[mode];
  $('#action-panel').innerHTML='<span class="eyebrow">LUMEN / TU AGENTE</span><h2>'+({followup:'Ya tiene el hilo.',voice:'Tu voz, con contexto.',meeting:'Llega con claridad.'}[mode])+'</h2><p class="fine">Para '+c.company+' · Tú revisas antes de usar.</p><div class="action-tabs" role="group" aria-label="Elegir acción">'+[['followup','Seguimiento'],['voice','Nota de voz'],['meeting','Reunión']].map(([id,label])=>'<button data-mode="'+id+'" class="'+(mode===id?'active':'')+'" aria-pressed="'+(mode===id)+'">'+label+'</button>').join('')+'</div>'+
  (mode==='voice'?voiceView(r):'<label class="field-label" for="tone">'+(mode==='meeting'?'Enfoque de la reunión':'Tono de la respuesta')+'</label><select id="tone">'+(mode==='meeting'?['Aclarar pendientes','Definir próximos pasos','Explorar necesidades']:['Directo y cercano','Breve y ejecutivo','Cálido y consultivo']).map(t=>'<option '+(r.tone===t?'selected':'')+'>'+t+'</option>').join('')+'</select><label class="field-label" for="instruction">¿Algo más que deba considerar?</label><textarea id="instruction" rows="2" placeholder="Opcional: añade un objetivo o un detalle…">'+escape(r.instruction||'')+'</textarea><button class="button generate" id="generate" '+(busy?'disabled':'')+'>'+(busy?'Preparando…':mode==='meeting'?'Preparar briefing':'Preparar seguimiento')+' <span>↗</span></button><button class="text-button" id="example">Usar guion de ejemplo</button>')+
  '<div id="action-error" role="status"></div>'+
  (draft?'<div class="result-meta"><span class="status-dot"></span>'+ (draft.source==='local'?'GENERADO · REVISIÓN PENDIENTE':'GUION DE EJEMPLO · EDITABLE')+'</div><label class="field-label" for="draft">Tu '+(mode==='voice'?'traducción':'borrador')+'</label><textarea id="draft" class="draft-text">'+escape(draft.text)+'</textarea><div class="result-actions"><button class="text-button" id="copy-draft">Copiar</button><button class="text-button" id="speak-draft">Escuchar</button><button class="text-button" id="save-draft">Guardar como nota</button><button class="text-button" id="export-draft">Descargar</button></div>':'')+
  '<details class="agreement-form" '+(draft?'open':'')+'><summary>Convertir en un acuerdo</summary><label class="field-label" for="task-title">Siguiente paso</label><input id="task-title" value="'+escape(r.taskTitle||c.task)+'"><div class="field-row"><label class="field-label">Responsable<input id="task-owner" value="'+escape(r.taskOwner||'Yo')+'"></label><label class="field-label">Fecha propuesta<input id="task-date" type="date" value="'+escape(r.taskDate||'')+'"></label></div><button class="button secondary generate" id="confirm-task">Confirmar acuerdo <span>✓</span></button><p class="fine">Se guarda en este espacio. No envía mensajes ni agenda eventos.</p></details>'+r.agreements.map((a,i)=>'<article class="agreement-card"><strong>'+escape(a.title)+'</strong><p>'+escape(a.owner)+' · '+(a.date?escape(a.date):'Fecha por confirmar')+'</p><button data-complete="'+i+'">'+(a.done?'✓ Completado':'Marcar como completado')+'</button></article>').join('');
  $('#tone')?.addEventListener('change',e=>{r.tone=e.target.value;save()});
  $('#instruction')?.addEventListener('input',e=>{r.instruction=e.target.value;save()});
  $('#draft')?.addEventListener('input',e=>{r.drafts[mode].text=e.target.value;save()});
  for(const [selector,field] of [['#task-title','taskTitle'],['#task-owner','taskOwner'],['#task-date','taskDate'],['#transcript','transcript'],['#target-language','target']])$(selector)?.addEventListener('input',e=>{r[field]=e.target.value;save()});
  $('#audio-file')?.addEventListener('change',e=>{const file=e.target.files[0];if(file)setAudio(file)});
  $('#action-panel').insertAdjacentHTML('afterbegin','<button class="text-button mobile-context-link" id="show-client-context">← Ver la conversación de '+escape(c.name.split(' ')[0])+'</button>');
  if(draft?.original&&mode==='voice'){const reference=document.createElement('details');reference.className='translation-reference';reference.innerHTML='<summary>Original de esta traducción · '+escape(draft.targetLanguage)+'</summary><p>'+escape(draft.original)+'</p>';$('#draft').after(reference)}
  if(audioURL&&mode==='voice')showAudio();
}
function voiceView(r){return '<div class="audio-capture"><button class="record-button" id="record-audio" aria-label="Grabar nota de voz">●</button><p class="audio-status" id="audio-status">Graba una idea. Conserva el detalle.</p><div class="audio-buttons"><label class="upload-label" for="audio-file">Subir audio</label><input type="file" accept="audio/*" id="audio-file" hidden><button class="text-button" id="sample-note">Usar nota de ejemplo</button></div><div id="audio-preview"></div></div><p class="fine">Hasta 5 minutos / 10 MB. El archivo se envía sólo al pulsar Transcribir. Puedes descartarlo.</p><label class="field-label" for="transcript">Transcripción · revisa antes de guardar</label><textarea id="transcript" rows="4" placeholder="Aquí aparecerá lo que dijiste…">'+escape(r.transcript)+'</textarea><div class="result-actions"><button class="text-button" id="save-transcript">Confirmar nota</button></div><label class="field-label" for="target-language">Traducir al</label><select id="target-language">'+['Español','English','Français','Português'].map(t=>'<option '+(r.target===t?'selected':'')+'>'+t+'</option>').join('')+'</select><button class="button generate" id="translate" '+(busy?'disabled':'')+'>Traducir texto revisado <span>↗</span></button>'}
function error(text){const el=$('#action-error');if(el){el.className='error-note';el.textContent=text}else toast(text)}
async function call(path,body){const response=await fetch(path,{method:'POST',headers:body instanceof FormData?{}:{'content-type':'application/json'},body:body instanceof FormData?body:JSON.stringify(body),signal:AbortSignal.timeout(60000)});const data=await response.json();if(!response.ok)throw new Error(data.error||'La operación no pudo completarse.');return data}
async function generate(translate=false){
  if(busy)return;const c=client(),r=record(),mode=state.mode,id=state.selected,run=++requestRun,original=r.transcript,targetLanguage=r.target;
  if(translate&&!r.transcript.trim())return error('Primero graba, escribe o carga una nota para traducir.');
  const message=translate?'Traduce fielmente al idioma '+r.target+' el siguiente texto. Entrega sólo la traducción, sin comentarios. Conserva nombres y cualquier incertidumbre. Texto:\n'+r.transcript:'Prepara '+(mode==='meeting'?'un briefing para una reunión con objetivo, contexto confirmado, tres preguntas y próximo paso propuesto':'un borrador de seguimiento para copiar, en el idioma del cliente')+'. Cliente: '+c.name+' / '+c.company+'. Idioma: '+c.language+'. Tono/enfoque: '+($('#tone')?.value||r.tone)+'. Consideración adicional: '+(r.instruction||'ninguna')+'\nCONVERSACIÓN DE EJEMPLO:\n'+c.messages.map(m=>(m.from==='me'?'Nosotros':c.name)+': '+m.text).join('\n')+'\nNOTAS CONFIRMADAS:\n'+r.notes.map(n=>n.text).join('\n');
  busy=true;renderAction();const indicator=document.createElement('div');indicator.className='busy-indicator';indicator.textContent=translate?'Traduciendo el texto revisado…':'Conectando contexto y preparando una propuesta…';$('#action-error').append(indicator);
  try{const data=await call('/api/chat',{message,task:translate?'translation':'draft'});if(run!==requestRun||id!==state.selected)return;r.drafts[mode]={text:data.text,source:'local',...(translate?{original,targetLanguage}:{})};save();toast(translate?'Traducción lista. El original se conserva.':'Propuesta lista para revisar.')}
  catch(e){if(run===requestRun){busy=false;renderAction();error(e.message+(translate?'':' También puedes usar el guion de ejemplo.'));return}}
  finally{if(run===requestRun)busy=false}
  if(run===requestRun)render();
}
function addNote(text){if(!text?.trim())return toast('Escribe una nota antes de confirmar.');const r=record();if(r.notes.some(n=>n.text===text.trim()))return toast('Esta nota ya está guardada.');r.notes.push({text:text.trim(),at:Date.now()});save();render();toast('Nota confirmada en el contexto de '+client().company+'.')}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Copiado. Listo para revisar y compartir.')}catch{toast('Selecciona el texto y cópialo con Ctrl + C.');$('#draft')?.select()}}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function speak(text){if(!('speechSynthesis' in window))return toast('Este navegador no tiene lectura de voz.');speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=state.mode==='voice'?({Español:'es-MX',English:'en-US',Français:'fr-FR','Português':'pt-BR'}[record().target]):client().language==='English'?'en-US':'es-MX';speechSynthesis.speak(utterance)}
function setAudio(blob){if(blob.size>10*1024*1024)return error('El audio supera 10 MB. Elige un archivo más breve.');if(audioURL)URL.revokeObjectURL(audioURL);audioBlob=blob;audioURL=URL.createObjectURL(blob);showAudio()}
function showAudio(){const el=$('#audio-preview');if(el)el.innerHTML='<audio class="audio-preview" controls src="'+audioURL+'"></audio><button class="button small" id="transcribe">Transcribir audio →</button> <button class="text-button" id="discard-audio">Descartar</button>';if($('#audio-status'))$('#audio-status').textContent='Audio listo. Escúchalo antes de transcribir.'}
function stopMeter(){cancelAnimationFrame(levelFrame);captureContext?.close().catch(()=>{});captureContext=null;$('.audio-level')?.remove()}
function startMeter(stream){
  try{const Context=window.AudioContext||window.webkitAudioContext;if(!Context)return;captureContext=new Context();const analyser=captureContext.createAnalyser();analyser.fftSize=64;captureContext.createMediaStreamSource(stream).connect(analyser);const values=new Uint8Array(analyser.frequencyBinCount),meter=document.createElement('div');meter.className='audio-level';meter.setAttribute('aria-hidden','true');meter.innerHTML=Array.from({length:20},()=>'<i></i>').join('');$('#record-audio').after(meter);const bars=[...meter.children],tick=()=>{analyser.getByteFrequencyData(values);bars.forEach((bar,i)=>bar.style.height=Math.max(3,values[i]*.15)+'px');levelFrame=requestAnimationFrame(tick)};tick()}catch{stopMeter()}
}
async function startRecording(){
  if(recording){recorder?.stop();return}
  if(busy)return toast('Espera a que termine la operación actual.');
  if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return error('El navegador no permite grabar aquí. Puedes subir un archivo de audio.');
  const run=++permissionRun;$('#record-audio').disabled=true;
  try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});if(run!==permissionRun){stream.getTracks().forEach(t=>t.stop());return}media=stream;chunks=[];const type=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(t=>MediaRecorder.isTypeSupported(t));recorder=new MediaRecorder(stream,type?{mimeType:type}:undefined);recording=true;let size=0;const start=Date.now();recorder.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);size+=e.data.size;if(size>10*1024*1024&&recorder.state==='recording')recorder.stop()}};recorder.onstop=()=>{clearInterval(recordTimer);stream.getTracks().forEach(t=>t.stop());recording=false;if(run!==permissionRun)return;setAudio(new Blob(chunks,{type:recorder.mimeType}));$('#record-audio')?.classList.remove('recording');if($('#record-audio')){$('#record-audio').textContent='●';$('#record-audio').setAttribute('aria-label','Grabar nota de voz')}};
    recorder.addEventListener('stop',stopMeter,{once:true});recorder.start(500);startMeter(stream);$('#record-audio').disabled=false;$('#record-audio').classList.add('recording');$('#record-audio').textContent='■';$('#record-audio').setAttribute('aria-label','Detener grabación');recordTimer=setInterval(()=>{const seconds=Math.floor((Date.now()-start)/1000);if($('#audio-status'))$('#audio-status').textContent='Grabando · '+Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')+' · Pulsa para detener';if(seconds>=300&&recorder.state==='recording')recorder.stop()},250);
  }catch{if(run===permissionRun){error('No se pudo acceder al micrófono. Revisa el permiso o sube un audio.');if($('#record-audio'))$('#record-audio').disabled=false}}
}
function cancelRecording(){permissionRun++;clearInterval(recordTimer);stopMeter();if(recorder?.state==='recording')recorder.stop();media?.getTracks().forEach(t=>t.stop());recording=false;audioBlob=null;if(audioURL)URL.revokeObjectURL(audioURL);audioURL=null;window.speechSynthesis?.cancel()}
async function transcribe(){
  if(!audioBlob||busy)return;busy=true;const run=++requestRun,id=state.selected;$('#transcribe').disabled=true;$('#audio-status').textContent='Transcribiendo con el runtime…';
  const form=new FormData(),extension=audioBlob.type.includes('mp4')?'m4a':audioBlob.type.includes('ogg')?'ogg':'webm';form.set('file',audioBlob,audioBlob.name||'nota.'+extension);
  try{const data=await call('/api/audio/transcriptions',form);if(run!==requestRun||id!==state.selected)return;record().transcript=data.text;save();$('#transcript').value=data.text;$('#audio-status').textContent='Transcripción lista. Revisa y confirma la nota.'}
  catch(e){if(run===requestRun){error(e.message+' Tu audio sigue disponible para reintentar.');$('#audio-status').textContent='No se completó la transcripción.'}}
  finally{if(run===requestRun){busy=false;if($('#transcribe'))$('#transcribe').disabled=false}}
}
function openSearch(){if(!workspaceOpen){login();return}showDialog('#palette');$('#search-input').value='';searchIndex=0;search();$('#search-input').focus()}
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function search(){const query=normalize($('#search-input').value.trim());searchItems=state.connected?[...clients.map(c=>({id:c.id,type:'client',title:c.name,sub:c.company+' · '+c.language,search:c.name+' '+c.company+' '+c.tags.join(' ')})),...[['followup','Preparar seguimiento'],['voice','Nueva nota de voz'],['meeting','Preparar reunión']].map(([id,title])=>({id,type:'action',title,sub:client().company,search:title}))]:[{id:'connect',type:'connect',title:'Añadir una conexión',sub:'Vista previa local',search:'anadir conexion conversaciones'}];searchItems=searchItems.filter(i=>normalize(i.search).includes(query));searchIndex=Math.max(0,Math.min(searchIndex,searchItems.length-1));$('#search-results').innerHTML=searchItems.length?searchItems.map((i,n)=>'<button class="search-result" id="result-'+n+'" role="option" aria-selected="'+(n===searchIndex)+'" data-result="'+n+'" tabindex="-1"><span class="tiny-icon">'+(i.type==='client'?'◎':'↗')+'</span><span><strong>'+escape(i.title)+'</strong><small>'+escape(i.sub)+'</small></span><span>↵</span></button>').join(''):'<p class="no-results">No encontramos coincidencias. Prueba con el nombre o la empresa.</p>';if(searchItems.length)$('#search-input').setAttribute('aria-activedescendant','result-'+searchIndex);else $('#search-input').removeAttribute('aria-activedescendant')}
function activateSearch(index){const item=searchItems[index];if(!item)return;closeDialogs();if(item.type==='connect')qr();else if(item.type==='client')selectClient(item.id);else{cancelRecording();requestRun++;busy=false;state.mode=item.id;save();renderAction();focusAction()}}
$('#search-input').addEventListener('input',()=>{searchIndex=0;search()});
$('#search-input').addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();searchIndex=(searchIndex+(e.key==='ArrowDown'?1:-1)+searchItems.length)%Math.max(1,searchItems.length);search();$('#result-'+searchIndex)?.scrollIntoView({block:'nearest'})}if(e.key==='Enter'){e.preventDefault();activateSearch(searchIndex)}});
async function health(){try{const data=await fetch('/api/health',{signal:AbortSignal.timeout(8000)}).then(r=>r.json());online=!!data.ai}catch{online=false}$('#runtime-status').textContent=online?'● Inteligencia conectada':'○ Runtime no disponible';$('#runtime-status').classList.toggle('online',online)}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}});
document.addEventListener('click',async e=>{
  const target=e.target.closest('button,a,label');if(!target)return;
  if(target.dataset.section!==undefined)navigate(+target.dataset.section);
  if(target.matches('[href="#inicio"]')){e.preventDefault();navigate(0)}
  if(target.hasAttribute('data-login'))login();
  if(target.hasAttribute('data-close'))target.closest('dialog').close();
  if(target.dataset.scenario)chooseScenario(target.dataset.scenario);
  if(target.hasAttribute('data-connect')||target.id==='connect-whatsapp')qr();
  if(target.hasAttribute('data-search'))openSearch();
  if(target.dataset.client)selectClient(target.dataset.client);
  if(target.dataset.result!==undefined)activateSearch(+target.dataset.result);
  if(target.id==='back-home')goHome();
  if(target.id==='show-client-context')$('#client-main').scrollIntoView({block:'start'});
  if(target.id==='show-scenarios')showDialog('#scenarios');
  if(target.id==='reset-demo'){$('#gateway-content').innerHTML='<span class="eyebrow">REINICIAR VISTA PREVIA</span><h2>Empezar<br>de nuevo.</h2><p>Se borrarán los borradores, notas y acuerdos guardados en este navegador. Puedes cancelar para conservarlos.</p><button class="button" id="confirm-reset">Reiniciar espacio</button><button class="text-button" data-close>Conservar mi trabajo</button>';showDialog('#gateway')}
  if(target.id==='confirm-reset'){cancelRecording();requestRun++;busy=false;state=blank();save();closeDialogs();render();toast('Espacio reiniciado.')}
  if(target.dataset.mode){cancelRecording();requestRun++;busy=false;state.mode=target.dataset.mode;save();renderAction()}
  if(target.id==='generate')generate();
  if(target.id==='translate')generate(true);
  if(target.id==='example'){requestRun++;busy=false;const c=client();record().drafts[state.mode]={text:c[state.mode],source:'example'};save();render()}
  if(target.id==='sample-note'){cancelRecording();requestRun++;busy=false;record().transcript=client().note;save();renderAction();toast('Nota de ejemplo cargada; no proviene de una grabación.')}
  if(target.id==='record-audio')startRecording();
  if(target.id==='transcribe')transcribe();
  if(target.id==='discard-audio'){cancelRecording();renderAction()}
  if(target.id==='save-transcript')addNote(record().transcript);
  if(target.id==='save-draft')addNote(record().drafts[state.mode]?.text);
  if(target.id==='copy-draft')copy(record().drafts[state.mode]?.text||'');
  if(target.id==='speak-draft')speak(record().drafts[state.mode]?.text||'');
  if(target.id==='export-draft')download(client().company+'\n\n'+(record().drafts[state.mode]?.text||''),client().id+'-'+state.mode+'.txt');
  if(target.id==='confirm-task'){const title=$('#task-title').value.trim(),owner=$('#task-owner').value.trim(),date=$('#task-date').value;if(!title||!owner)return toast('Escribe el siguiente paso y quién se responsabiliza.');if(record().agreements.some(a=>a.title===title&&!a.done))return toast('Ese acuerdo ya está guardado.');record().agreements.push({title,owner,date,done:false});save();render();toast('Acuerdo confirmado. El siguiente paso ya está visible.')}
  if(target.dataset.complete!==undefined){record().agreements[+target.dataset.complete].done=!record().agreements[+target.dataset.complete].done;save();renderAction()}
  if(target.dataset.deleteNote!==undefined){record().notes.splice(+target.dataset.deleteNote,1);save();render()}
});
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
document.addEventListener('visibilitychange',()=>{if(document.hidden&&recording)recorder?.stop()});
health();
